import { useContext, useState } from "react";
import { api } from "../api";
import { Session, SessionChanged } from "../App";

/**
 * Your own account — the two things nobody else can do for you.
 *
 * Separate from the accounts page on purpose. That one is the server's list of
 * people and it is admin-only; this is one person changing their own password
 * and their own name, and a builder must be able to reach it. The first password
 * on a machine is generated by `laneyard setup` and printed once, so this is
 * where it stops being a random string somebody wrote on a sticky note.
 */
export function Account() {
  const me = useContext(Session);
  const sessionChanged = useContext(SessionChanged);

  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [again, setAgain] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  // The name form keeps its own current-password field: it is a separate act,
  // and one form's password should not stand in for the other's.
  const [nameCurrent, setNameCurrent] = useState("");
  const [nextName, setNextName] = useState("");
  const [namingSaving, setNamingSaving] = useState(false);
  const [nameError, setNameError] = useState<string | null>(null);
  const [nameDone, setNameDone] = useState(false);

  // Checked here as well as on the server, because it is the one refusal the
  // browser can give while the second field is still being typed. Everything
  // else — too short, wrong current password — is the server's sentence.
  const mismatch = again !== "" && next !== again;

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSaving(true);
    setError(null);
    try {
      await api.changeOwnPassword(current, next);
      // Out of the fields the moment it is stored: nothing to read over a
      // shoulder, and no form that can be submitted twice by accident.
      setCurrent("");
      setNext("");
      setAgain("");
      setDone(true);
    } catch (e) {
      setDone(false);
      setError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  const submitName = async (event: React.FormEvent) => {
    event.preventDefault();
    setNamingSaving(true);
    setNameError(null);
    try {
      await api.setAccountName(nameCurrent, nextName);
      setNameCurrent("");
      setNextName("");
      setNameDone(true);
      // The server set a fresh cookie under the new name; this is what makes the
      // header and this page follow it rather than keep showing the old one.
      sessionChanged();
    } catch (e) {
      setNameDone(false);
      setNameError((e as Error).message);
    } finally {
      setNamingSaving(false);
    }
  };

  return (
    <>
      <h2 className="section">your account</h2>
      <p className="dim">
        signed in as <span className="bright">{me?.name}</span>{" "}
        <span className="dim">{me?.role}</span>. your password and your name are the two things this
        page changes, and the two things nobody else can change for you.
      </p>

      <h2 className="section" style={{ marginTop: 20 }}>
        change password
      </h2>
      <form className="secret-form" onSubmit={(e) => void submit(e)}>
        <input
          type="password"
          value={current}
          onChange={(e) => setCurrent(e.target.value)}
          placeholder="current password"
          autoComplete="current-password"
          aria-label="current password"
        />
        <input
          type="password"
          value={next}
          onChange={(e) => setNext(e.target.value)}
          placeholder="new password"
          autoComplete="new-password"
          aria-label="new password"
        />
        <input
          type="password"
          value={again}
          onChange={(e) => setAgain(e.target.value)}
          placeholder="again"
          autoComplete="new-password"
          aria-label="new password again"
        />
        <button
          type="submit"
          disabled={saving || current === "" || next === "" || next !== again}
        >
          change
        </button>
      </form>

      {mismatch && <p className="status-failed">the two new passwords are not the same.</p>}

      {/* Said before it happens rather than discovered as a phone that went
          back to the login form for no reason anyone can explain. */}
      <p className="dim">
        the new password is hashed into this machine's config.yml. every other session this account
        has ends at once — a phone, another browser — and this page stays signed in.
      </p>
      <p className="dim">
        the current password is asked for even though you are already signed in: a session is a
        cookie in a browser that may have been left open.
      </p>

      {done && (
        <p>
          <span className="mark accent">✓</span> <span className="dim">password changed.</span>
        </p>
      )}
      {error && <p className="status-failed">refused — {error}</p>}

      <h2 className="section" style={{ marginTop: 20 }}>
        change your identifier
      </h2>
      <form className="secret-form" onSubmit={(e) => void submitName(e)}>
        <input
          type="password"
          value={nameCurrent}
          onChange={(e) => setNameCurrent(e.target.value)}
          placeholder="current password"
          autoComplete="current-password"
          aria-label="current password to change name"
        />
        <input
          type="text"
          value={nextName}
          onChange={(e) => setNextName(e.target.value)}
          placeholder="new name"
          autoComplete="off"
          aria-label="new name"
        />
        <button
          type="submit"
          disabled={namingSaving || nameCurrent === "" || nextName === "" || nextName === me?.name}
        >
          change
        </button>
      </form>

      {/* Said before it happens, like the password: renaming ends every other
          session too, since the server matches a session's name against a live
          account and after this there is none by the old name. */}
      <p className="dim">
        your name is what you type into the login form. changing it here edits this machine's
        config.yml and keeps your role and your project access exactly as they were. every other
        session ends, and this page stays signed in under the new name.
      </p>
      <p className="dim">
        the current password is asked for here too: a session is a cookie in a browser that may have
        been left open.
      </p>

      {nameDone && (
        <p>
          <span className="mark accent">✓</span> <span className="dim">name changed.</span>
        </p>
      )}
      {nameError && <p className="status-failed">refused — {nameError}</p>}
    </>
  );
}
