import { useContext, useState } from "react";
import { api } from "../api";
import { Session } from "../App";

/**
 * Your own account — which today means the one thing nobody else can do for you.
 *
 * Separate from the accounts page on purpose. That one is the server's list of
 * people and it is admin-only; this is one person changing their own password,
 * and a builder must be able to reach it. The first password on a machine is
 * generated by `laneyard setup` and printed once, so this is where it stops
 * being a random string somebody wrote on a sticky note.
 */
export function Account() {
  const me = useContext(Session);

  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [again, setAgain] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  // Checked here as well as on the server, because it is the one refusal the
  // browser can give while the second field is still being typed. Everything
  // else — too short, wrong current password — is the server's sentence.
  const mismatch = again !== "" && next !== again;

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSaving(true);
    setError(null);
    try {
      await api.changeOwnPassword(current, next);
      // Out of the fields the moment it is stored: nothing to read over a
      // shoulder, and no form that can be submitted twice by accident.
      setCurrent("");
      setNext("");
      setAgain("");
      setDone(true);
    } catch (e) {
      setDone(false);
      setError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <h2 className="section">your account</h2>
      <p className="dim">
        signed in as <span className="bright">{me?.name}</span>{" "}
        <span className="dim">{me?.role}</span>. the name is fixed — an admin makes another one.
      </p>

      <h2 className="section" style={{ marginTop: 20 }}>
        change password
      </h2>
      <form className="secret-form" onSubmit={(e) => void submit(e)}>
        <input
          type="password"
          value={current}
          onChange={(e) => setCurrent(e.target.value)}
          placeholder="current password"
          autoComplete="current-password"
          aria-label="current password"
        />
        <input
          type="password"
          value={next}
          onChange={(e) => setNext(e.target.value)}
          placeholder="new password"
          autoComplete="new-password"
          aria-label="new password"
        />
        <input
          type="password"
          value={again}
          onChange={(e) => setAgain(e.target.value)}
          placeholder="again"
          autoComplete="new-password"
          aria-label="new password again"
        />
        <button
          type="submit"
          disabled={saving || current === "" || next === "" || next !== again}
        >
          change
        </button>
      </form>

      {mismatch && <p className="status-failed">the two new passwords are not the same.</p>}

      {/* Said before it happens rather than discovered as a phone that went
          back to the login form for no reason anyone can explain. */}
      <p className="dim">
        the new password is hashed into this machine's config.yml. every other session this account
        has ends at once — a phone, another browser — and this page stays signed in.
      </p>
      <p className="dim">
        the current password is asked for even though you are already signed in: a session is a
        cookie in a browser that may have been left open.
      </p>

      {done && (
        <p>
          <span className="mark accent">✓</span> <span className="dim">password changed.</span>
        </p>
      )}
      {error && <p className="status-failed">refused — {error}</p>}
    </>
  );
}
